pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - approved-reviews-by!=github-actions
      - label!=WIP
    actions:
      merge:
        method: merge
  - name: automatic merge for Dependabot pull requests
    conditions:
      - check-success=build
      - author~=^dependabot(|-preview)\[bot\]$
      - label!=WIP
    actions:
      merge:
        method: merge
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: "This pull request is now in conflicts. @{{ author }}, could you fix it? 🙏"