sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
env:
  global:
    - REGISTRY_USER=vektory79
    - secure: O/95s6gXArjWGU88xiiITSfdjL4HJ4cJxURDs0l2OrhTVPGO/hmuGAIFZBE8znOozc+C7r6m5PYDM+PdPsSQdLJZ+cH9xGfLpfjYA38DMP6KKWP8jfbN1XFqLDN5YjqNOL6tPSx+f26UGvK7u2eTHvfPKq6x3W8mxx3y3jtI11vXMsc9TMpmg0ClBbAEiB8/8xwSsA9yIwHrtzq0khm9Vbdlh/2xYSddTFpM/HPUkud2fqWO8fkUFZVz0apMOTyfc+AzUgtE60Uo9LYQzcdVxUdv0MDA9/9qKy45Si6yKTu9iyOIpoN6YChjoExKE1q/xyXjl+vH1fIcRlRsOg3Ce7U3r+LaPk46IYVyxdgAlOe/VIh9GZLMgmlbjGMRXI2mcvvokRNI0gU2c5Ur6Y01727d10oJnnVU1a+/8J6gAz2y6UoHHnxTmZXFYaAF7Ud0hRaPIp+GtO+z7aqhE8U+gMMpnzhXLfTE1BYtRZareQ2r1BEfBFc5TiFCaGLQ/jK/incbV8g/Iv6tw5USx9oJ6nfWFwkXYN249Mb5nm4OAsUE+RuiN9LsX+wKiQNvszIzW9MIoE+CWeOrc4elq9hCXMcKbRcjIBgjHFYc/7DxEBiDXJ0W0fL+VAJJ3FGm+dh3UJGnklQojvIpFEtxBOX0JEIPW0jCWr8hegFHIomYw/w=
script:
  - ./build.sh -pc
  - docker run javister-docker-docker.bintray.io/javister/javister-docker-base my_init -- ls

after_script:
  - docker images
before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin

deploy:
  provider: script
  script: ./build.sh -rdc
  on:
    branch: master
