sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
script:
  - ./build.sh
  - docker run javister-docker-docker.bintray.io/javister/javister-docker-base my_init -- ls

after_script:
  - docker images