sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
env:
  global:
    - REGISTRY_USER=vektory79
before_script:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin javister-docker-docker.bintray.io
script:
  - ./build.sh -rpc
  - docker run javister-docker-docker.bintray.io/javister/javister-docker-base my_init -- ls

after_script:
  - docker images

deploy:
  provider: script
  script: ./build.sh -rdc
  on:
    branch: master
