#!/bin/sh
set -e

SYSLOGNG_OPTS=":-${SYSLOGNG_OPTS}"

[ -r /etc/default/syslog-ng ] && . /etc/default/syslog-ng

case "x${CONSOLE_LOG_LEVEL}" in
  x[1-8])
    dmesg -n ${CONSOLE_LOG_LEVEL}
    ;;
  x)
    ;;
  *)
    merror "CONSOLE_LOG_LEVEL is of unaccepted value."
    ;;
esac

touch /tmp/SYSLOG_STARTED

exec syslog-ng -F -p /var/run/syslog-ng.pid ${SYSLOGNG_OPTS}
