name: Build master branch
on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: bintray-javister
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Cache Maven packages
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Check
        run: mvn --no-transfer-progress -Dstyle.color=always --fail-at-end verify
        env:
          MAVEN_USERNAME: ${{ secrets.BINTRAY_USER }}
          MAVEN_PASSWORD: ${{ secrets.BINTRAY_PASSWORD }}
          MAVEN_OPTS: -Djansi.force=true

      - name: Upload report files
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-results
          path: ./target/allure-results


  publish-report:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - name: Download report files
        uses: actions/download-artifact@v2
        with:
          name: allure-results
          path: ./target/allure-results
      # Thanks to @simple1elf (Telegram) for the working template
      # https://github.com/simple-elf/github-allure-history
      - name: Get Allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        #uses: ./allure-report-action
        #id: allure-report
        with:
          allure_results: 'target/allure-results'
          allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-history
          publish_branch: gh-pages
